### ISSUE TITLE
dRegions: Mob related flags

### ISSUE THREAD

**Issue by OzOwnz** [AnthonyAMC/Public-Denizen-Scripts#37]
Have it seamlessly added to their AI as if the region was an invisible wall. (Show blocks to their AI?)

:D

**Comment by mcmonkey4eva** [comment]
Also whether players can damage mobs.

**Comment by mcmonkey4eva** [comment]
Also some form of option switch related to NPCs as mobs. Like whether each flag should apply to NPC mobs as well

**Comment by AnthonyAMC** [comment]
I've been thinking about an NPC check as well, but didn't nail down the right method yet.

**Comment by AnthonyAMC** [comment]
Most mob related flags are handled now with the exception of mob-entry. NPCs haven't be specifically dealt with in any regards yet. Open new issues as needed.
