### ISSUE TITLE
dRegions: better setup system

### ISSUE THREAD

**Issue by mcmonkey4eva** [AnthonyAMC/Public-Denizen-Scripts#38]
The engine should set itself up on reload scripts, no need to run a script manually or anything like that

**Comment by AnthonyAMC** [comment]
Is a [restart command](https://github.com/AnthonyAMC/Public-Denizen-Scripts/commit/8c1ec2ec84602024ee14a319121b8bf58ed13c87) sufficient?

**Comment by mcmonkey4eva** [comment]
well, first, that should definitely respond with:
`Warning: this will reset all your dRegions data! Are you sure? Type "/dregions restart CONFIRM" to confirm.`
second, no, it should first-time load automatically on script reload.
IE
```
on script reload:
- if !<server.flag[dregions_loaded]> {
- start
}
```

**Comment by AnthonyAMC** [comment]
That warning /would/ be necessary if it overwrote any existing data, but it doesn't. It just runs through it's internal init process which only creates missing files. I /could/ add a ```reset``` command that would reset everything in one shot.

Wouldn't you have to ```/denizen reload scripts``` twice for it to take effect? Once to get the script loaded, and then again for the on script reload event to fire now that it's registered.

**Comment by mcmonkey4eva** [comment]
script reload event fires for newly loaded scripts.

**Comment by AnthonyAMC** [comment]
Good to know. Will do then.

**Comment by AnthonyAMC** [comment]
Can this be closed with https://github.com/AnthonyAMC/Public-Denizen-Scripts/commit/10ea84ba19badeea68e49ab080d043eae74eab1a
