### ISSUE TITLE
dRegions: less permission reliance

### ISSUE THREAD

**Issue by mcmonkey4eva** [AnthonyAMC/Public-Denizen-Scripts#39]
The engine shouldn't do things like check the `<player.groups>` tag when not needed. Because some people don't use permission plugins.

**Comment by AnthonyAMC** [comment]
Agreed. The initial setup for permissions didn't account for op-only scenarios at all. The things just added (see previous commits) are patches for right now until i map out an appropriate permissions pre-processor.

**Comment by AnthonyAMC** [comment]
Do the patches fix the blockages? I know build requires you to be at least a member of __global__

**Comment by AnthonyAMC** [comment]
Can this be closed with https://github.com/AnthonyAMC/Public-Denizen-Scripts/commit/10ea84ba19badeea68e49ab080d043eae74eab1a

**Comment by mcmonkey4eva** [comment]
```ERROR! No permission system loaded! Have you installed Vault
  and a compatible permissions plugin?``` when trying to break a block.

**Comment by AnthonyAMC** [comment]
That's annoying. Does it prevent block breaking completely?
