### ISSUE TITLE
dRegions: automatically add owner when a new region is created

### ISSUE THREAD

**Issue by mcmonkey4eva** [AnthonyAMC/Public-Denizen-Scripts#40]
I know WG doesn't do this, but we're better than WG here. Adding the owner is seriously straightforward logic, why would you ever not do this?

**Comment by AnthonyAMC** [comment]
It's [already there](https://github.com/AnthonyAMC/Public-Denizen-Scripts/blob/master/dRegions/dRegions.dscript#L1072), i just have it commented out while i'm deving. More often than not i don't want to be a region owner/member while testing
