### ISSUE TITLE
dWE: Undo fails

### ISSUE THREAD

**Issue by mcmonkey4eva** [AnthonyAMC/Public-Denizen-Scripts#42]
Undo shouts 'Undo Complete!' but doesn't actually undo my basic cuboid /dwe set

**Comment by AnthonyAMC** [comment]
It was working prior to [this](https://github.com/AnthonyAMC/Public-Denizen-Scripts/commit/57a9e840d111f5e7f5352147d20bfa0658bacbcf) and [this](https://github.com/AnthonyAMC/Public-Denizen-Scripts/commit/8837a73754d5c52cb99ae751a7f059baae6a5cc3). I (unfortunately) didn't test on that commit.

**Comment by AnthonyAMC** [comment]
Undo works as expected
