### ISSUE TITLE
dRegions: death drops flag

### ISSUE THREAD

**Issue by mcmonkey4eva** [AnthonyAMC/Public-Denizen-Scripts#51]
A flag for droppings items/xp on death, preferrably per-entity-type

**Comment by AnthonyAMC** [comment]
Per entity as in living entities and players. So for players, maybe keep items on death, or just no drop on death?

**Comment by mcmonkey4eva** [comment]
Flags for each! :D

**Comment by AnthonyAMC** [comment]
entiti-drops-ondeath and entity-drops-ondeathlist cover mobs dropping items. player-drops-ondeath covers players dropping items. And what the hell, let's let players be able to keep items on death too with player-keepitems
