### ISSUE TITLE
QuestGUI : How set accents ?

### ISSUE THREAD

**Issue by Oruss7** [AnthonyAMC/Public-Denizen-Scripts#63]
I'm french, so i have `ê é à ç` etc.

And i use `<&chr[00EA]>` with iso code for letters with accents. 
Working well but not in quest item (maybe yaml pb?)

![sans titre](https://cloud.githubusercontent.com/assets/4788317/14769561/b5430258-0a5b-11e6-8877-bc5d18c694d6.png)

Thanks to help me.

**Comment by AnthonyAMC** [comment]
I could possibly pass all output through `<parse:>` but i was really trying to avoid that for potential badness that would surely follow. Please try using the characters directly in your configs first. If that doesn't work for some strange reason, I can show you how to make the modification.

**Comment by Oruss7** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/4788317/14769809/a0506cf4-0a61-11e6-870b-826b4ad7aa26.png)

**Comment by mcmonkey4eva** [comment]
Check that your config is encoded correctly - Generally you want "UTF-8 Without BOM" but sometimes need "ANSI"

**Comment by Oruss7** [comment]
Use UTF-8 without BOM.
