### ISSUE TITLE
MessageConstructorLibrary: Feature Request - Automatic clickable links

### ISSUE THREAD

**Issue by AnthonyAMC** [AnthonyAMC/Public-Denizen-Scripts#65]
MCL should provide a way for narrate, announce, and anything in msgBoxed to have clickable links automatically with a simple format for the end users. Maybe something like:
```
- narrate "Hey, click @url|this|mcmonkey.org link!"
```

**Comment by calico-kid** [comment]
Maybe a URL tag like <url[www.example.com<http://www.example.com>]> just a thought to keep things in format with the reg denizen stuff

Sent from my iPhone

On May 25, 2016, at 7:31 PM, AnthonyAMC <notifications@github.com<mailto:notifications@github.com>> wrote:


MCL should provide a way for narrate, announce, and anything in msgBoxed to have clickable links automatically with a simple format for the end users. Maybe something like:

- narrate "Hey, click @url|this|mcmonkey.org<http://mcmonkey.org> link!"


-

**Comment by AnthonyAMC** [comment]
@calico-kid That would fail for 2 reasons. Denizen would try to read it as a tag, and then as a tag within a tag lol. We'd need another way to denote a url.

**Comment by mcmonkey4eva** [comment]
I'd make it `- narrate "Hey, click <proc[chat_url].context[this|mcmonkey.org]> link!"`

**Comment by mcmonkey4eva** [comment]
then the proc does like... special hidden color codes and stuff to indicate and separate the content. So you can more safely ensure it won't happen from strange chat / chat plugin nonsense.

**Comment by AnthonyAMC** [comment]
@mcmonkey4eva In order for clicking text to work it must be json. We need to intercept the narrates and replace them with our own json. How does a proc help achieve this?

**Comment by mcmonkey4eva** [comment]
@AnthonyAMC the proc would return EG `<&a><&b><&c>@@@URL:<def[text].escaped>|<def[url].escaped>`
This would:
- Provide a more sane interface (tags are life)
- Avoid bad interceptions (EG a player typing `@url...` into chat)

**Comment by mcmonkey4eva** [comment]
Additionally, in the case of chat being colorable... `<red.substring[1,1]>Q` returns a non-color code that only a plugin can ever type.
