### ISSUE TITLE
dWE: Schematic Command

### ISSUE THREAD

**Issue by Xenmai** [AnthonyAMC/Public-Denizen-Scripts#67]
It can be used like /dwe schematic banana, meaning your current selection (pos1&pos2) gets saved as a schematic with the name "banana".
I know I can do it myself, and I am right now with:

```
on schem command:
      - determine passively fulfilled
      - define pos1 <player.flag[dWEWand].as_list.get[1]||null>
      - define pos2 <player.flag[dWEWand].as_list.get[2]||null>
      - define cuboid cu@%pos1%|%pos2%
      - schematic create name:<context.args.get[1]> <def[cuboid]> <def[pos1]>
      - schematic save name:<context.args.get[1]>
```

It lets me do /schem banana to create such schematic easily.
I just think it'd be a good feature to add, and shouldn't be hard to integrate at all.

**Comment by AnthonyAMC** [comment]
Yeah it's not a big deal to add. I've been putting it off for a while now, i suppose i'll add it tonight.
