### ISSUE TITLE
Message Constructor Lib. Invalide character proc msgChat

### ISSUE THREAD

**Issue by Oruss7** [AnthonyAMC/Public-Denizen-Scripts#68]
I can't use some characters:
- `,`

Example:
`- narrate "<blue>► <proc[msgChat].context[<blue>Oui, je recherche un travail|oui|Acceptez le travail]>"`

output:
![capture](https://cloud.githubusercontent.com/assets/4788317/17650973/2b6b609e-625c-11e6-9e88-288c70daf781.PNG)

**Comment by mcmonkey4eva** [comment]
Might have to `.unescaped` the output? 0.o

**Comment by AnthonyAMC** [comment]
Nope. The comma is a JSON special character, and also a special character in [MCL](https://github.com/AnthonyAMC/Public-Denizen-Scripts/blob/master/MessageConstructors.yml#L387). I'm not sure what i can do about that.

**Comment by mcmonkey4eva** [comment]
escaping magic :O : O :O

**Comment by AnthonyAMC** [comment]
@mcmonkey4eva yeah, perhaps if the user escaped the strings they supply to mcl i could return unescaped data.
