### ISSUE TITLE
mcmonkey url change

### ISSUE THREAD

**Issue by BlackCoyote** [AnthonyAMC/Public-Denizen-Scripts#71]
``<BlackCoyote> he has to change the webget from
<BlackCoyote>       - ~webget "http://www.mcmonkey.org/denizen/repo/version/<s@dRegions_Version.yaml_key[id]>" save:page
<BlackCoyote> to
<BlackCoyote>       - ~webget "http://old.mcmonkey.org/denizen/repo/version/<s@dRegions_Version.yaml_key[id]>" save:page````

**Comment by AnthonyAMC** [comment]
Thanks for posting since nothing was mentioned anywhere else except irc.
