### ISSUE TITLE
word choice issue, perhaps

### ISSUE THREAD

**Issue by Zodzie** [AnthonyAMC/Public-Denizen-Scripts#72]
ERROR! Invalid path specified. Invalid paths have been denied
                   by the server administrator.

Potentially, this meant to say " ERROR! Invalid path specified. Invalid paths have been defined by the server administrator"   or perhaps, permissions denied by server

**Comment by mcmonkey4eva** [comment]
That error means you put something in an invalid path (EG the `scripts` folder), which "the server administrator" has denied. (Technically, the config.yml defaults have denied it!)

This has nothing to do with Anthony's scripts.

**Comment by AnthonyAMC** [comment]
My scripts that do save data stay within `plugins/Denizen` so idk where you're saving scripts to...
