### ISSUE TITLE
some incorrect information

### ISSUE THREAD

**Issue by Zodzie** [AnthonyAMC/Public-Denizen-Scripts#73]
https://github.com/AnthonyAMC/Public-Denizen-Scripts/blob/master/dRegions/dRegions.yml

> Install Flags, ConfigFileGenerator, dWorldEditor, and dRegions to your scripts folder and reload scripts. /denizen reload scripts

Don't forget commands.yml && MessageConstructors.yml!! 

Thanks

**Comment by AnthonyAMC** [comment]
Old comments yeah i suppose i should update for those that actually read the script files.

**Comment by AnthonyAMC** [comment]
Fixed in 050c16d85205b332b75c282f86d18c0f74267800
