### ISSUE TITLE
Execute as message not Command? [msgcommand].context

### ISSUE THREAD

**Issue by TheSodaPopPanda** [AnthonyAMC/Public-Denizen-Scripts#75]
HI, I'm back :nerd_face:  I have a question I am playing with you message lib, and I noticed that
it adds the / when you use [msgcommand] I wanted to use this with chat trigger for conversations with NPC's, is there a way around this, more likely you have a better way to trigger the NPC using clickable text.
(:spiral_notepad: I did look ay GUI's and the Scroller but I would still like ti use chat :smile: )

**Comment by AnthonyAMC** [comment]
This question was answered in irc
```
- narrate "hey click <proc[msgChat].context[this|you did it!|click here mofo]>"
```
