### ISSUE TITLE
Quests GUI Support

### ISSUE THREAD

**Issue by Arctomium** [AnthonyAMC/Public-Denizen-Scripts#76]
Hey I was wondering if you could integrate your QuestsGUI script with [Quests](https://www.spigotmc.org/resources/quests.3711/
) since Denizen and Citizens use that plugin as the primary questing plugin.

**Comment by AnthonyAMC** [comment]
I'm not sure how best to respond to this...
Neither Denizen nor Citizens *use* the Quests plugin... Denizen provides some support for it via depenizen. Quests uses the CitizensAPI for npc functions. QuestGUI is a denizen script that supports quests written in denizen script. There's no (sane) way for me to add support for the Quests plugin.
