### ISSUE TITLE
msgChat but

### ISSUE THREAD

**Issue by ColonelOverspel** [AnthonyAMC/Public-Denizen-Scripts#79]
Hi Anthony,
ther is a small problem with the msgChat option. When you write a comma in the output section, it will return something that does not make sense.
Great script! Keep up the gud work!!

**Comment by AnthonyAMC** [comment]
That should have been fixed in #14682dd
Let me know if this is still an issue

**Comment by AnthonyAMC** [comment]
Confirmed fixed.
