### ISSUE TITLE
dRegions: Consider TNT, etc. to be block changes

### ISSUE THREAD

**Issue by mcmonkey4eva** [AnthonyAMC/Public-Denizen-Scripts#83]
If block break is denied, you shouldn't be able to detonate TNT or otherwise interact with special-case blocks that will result in a block being visibly externally modified.

Present case in current dRG is... 'yeah you can totally just detonate TNT'

My dRG-protected world was imported from WorldGuard settings, so... TNT should definitely have been disabled just by virtue of exact-copying.

**Comment by AnthonyAMC** [comment]
As the default setting for a defined/claimed region, or you mean the global region?

**Comment by mcmonkey4eva** [comment]
as part of any region that denies block break in any form. IE the block break prevention flags should include tnt ignition, etc.
