### ISSUE TITLE
dWorldManager

### ISSUE THREAD

**Issue by OpalMoonstride** [AnthonyAMC/Public-Denizen-Scripts#87]
I have been searching through world management and instancing scripts and I thought I would give yours a go. 

Is this still intended to be supported/viable? I have the errors, as shown in my images, when I try it on a fresh dev server. 

Also, is it possible to add instancing support, or was that already intended? If it's not in, I am willing to throw money at someone to make that happen. I tried another script for instancing, by BlackCoyote, but it doesn't support creation of The End, or The Nether, for instancing. 

Thanks, so much!
https://pastebin.com/DHHB4L5P

![dworldmanagererror01](https://user-images.githubusercontent.com/39387146/42713689-554c13e4-86be-11e8-87ab-ee1f7903b118.png)
![dworldmanagererror02](https://user-images.githubusercontent.com/39387146/42713694-58f75652-86be-11e8-87df-804e2b4c9648.PNG)

**Comment by AnthonyAMC** [comment]
Setting [this](https://github.com/DenizenScript/Denizen-For-Bukkit/blob/master/plugin/src/main/resources/config.yml#L127) to true should fix the error.

Sorry for the late reply... I'm a bit out of the loop these days.

**Comment by AnthonyAMC** [comment]
The second image is the result of not having any dwm permissions. I should have handled the empty list better
